os: linux
language: c
script: TRAVIS_MODE=1 ./scripts/build-release
# Need all history to build change log.
git:
  depth: false
  quiet: true
matrix:
  include:
  - name: gcc-4.9
    env:
      - CC=gcc-4.9
      - STP_BUILD_OPERATIONS='preflight run_build_fresh run_distcheck_fast run_valgrind_fast'
  - name: gcc-7
    env:
      - CC=gcc-7
      - STP_BUILD_OPERATIONS='run_build_fresh run_distcheck_fast run_valgrind_fast'
  - name: gcc-8
    env:
      - CC=gcc-8
      - STP_CONFIG_ARGS=--disable-static
      - STP_BUILD_OPERATIONS='run_build_fresh run_distcheck_fast run_valgrind_fast'
  - name: clang-3.8
    env:
      - CC=clang-3.8
      - STP_BUILD_OPERATIONS='run_build_fresh run_distcheck_fast run_valgrind_fast'
  - name: checksums
    env:
      - STP_BUILD_OPERATIONS='run_build_fresh run_checksums'
      - STP_CONFIG_ARGS='--disable-nls --without-gimp2 --without-doc --without-cups --disable-libgutenprintui2 --disable-escputil'
      - STP_TEST_ROTOR=0
      - STP_TEST_ROTOR=1
      - STP_TEST_ROTOR=2
      - STP_TEST_ROTOR=3
      - STP_TEST_ROTOR=4
      - STP_TEST_ROTOR=5
      - STP_TEST_ROTOR=6
      - STP_TEST_ROTOR_CIRCUMFERENCE=7
      - STP_MIN_CHECKSUM_PREFIX=0
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - autoconf
          - autogen
          - automake
          - autopoint
          - bison
          - bzip2
          - flex
          - time
          - xz-utils
          - zpaq
notifications:
  email:
    recipients:
    - rlk@alum.mit.edu
    on_success: always
    on_failure: always
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - autoconf
    - autogen
    - automake
    - autopoint
    - bison
    - bzip2
    - cups-filters
    - cups-filters-core-drivers
    - cups-client
    - docbook
    - docbook-dsssl
    - docbook-simple
    - docbook-utils
    - docbook-xml
    - docbook-xsl
    - doxygen
    - dvips-fontdata-n2bk
    - flex
    - gcc-4.9
    - gcc-7
    - gcc-8
    - clang-3.8
    - gettext
    - imagemagick
    - jade
    - jadetex
    - libcups2-dev
    - libcupsimage2-dev
    - libgimp2.0-dev
    - libtool
    - libusb-1.0-0-dev
    - openjade
    - pdfjam
    - perl
    - sgml-base
    - sgml-data
    - sgmltools-lite
    - texi2html
    - time
    - valgrind
    - xz-utils
    - zpaq
